apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 8f7ebbf6-6fe9-4857-9d69-c734a4b79df5
  name: kustomize-example
spec:
  template:
    spec:
      containers:
      - image: gcr.io/vic-cloud-run-kustomize-1/kustomize-example:b8a3d5ba01ad5e7dbbc92c5c4dcb41754e8139eca2ffa7ab66f308ee1b150836
