apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: cloud-run-kustomize
build:
  googleCloudBuild: {}
  artifacts:
  - image: kustomize-example
    context: src/
deploy:
  kustomize:
    paths:
    - dev/
profiles:
  - name: prod
    deploy:
      kustomize:
        paths: 
        - prod/
